name: Push to master - CI & CD

on:
  push:
    branches: [master]

jobs:
  build:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install packages
        run: yarn

      - name: Lint project
        run: yarn lint

      - name: Test project
        run: yarn test

      - name: Build project
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
