name: Push to master - CI & CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup NodeJS v16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install packages
        run: yarn

      - name: Lint project
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Test project
        run: yarn test

